kind: live
name: Neu.ro WebDAV server
author: Neu.ro MLOps team (Yevhenii Semendiak)
descr: Serve your Neu.ro volume with rclone WebDAV server

inputs:
  volume_remote:
    descr: |
      Reference to the target volume to serve.
  http_auth:
    default: ""
    descr: |
      Whether to enable Neu.ro platform-based authentication or not.
      If disabled (set to "" by default) - your WebDAV will not be protected by Neu.ro SSO.
      It has no impact on `rclone serve webdav` parameters though.
  port:
    default: "8080"
    descr: |
      Rclone WebDAV server port.
      Useful if you want to access the server within the cluster, for instance, from another job.
  job_name:
    default: "webdav"
    descr: |
      The name of WebDAV server.
      Use it to generate a predictable job hostname.
  job_lifespan:
    default: "1d"
    descr: |
      The amount of time to run WebDAV server job container.
  preset:
    default: cpu-small
    descr: |
      The amount of resources to use, while running the server.
  extra_params:
    default: ""
    descr: |
      Extra parameters for `rclone serve webdav` command invocation.

job:
  image: rclone/rclone:1.53.2
  name: ${{ inputs.job_name }}
  preset: ${{ inputs.preset }}
  life_span: ${{ inputs.job_lifespan }}
  http_port: ${{ inputs.port }}
  http_auth: ${{ inputs.http_auth }}
  detach: True
  volumes:
    - ${{ inputs.volume_remote }}:/webdav_dir:rw
  cmd: |
    serve webdav /webdav_dir --addr :${{ inputs.port }} ${{ inputs.extra_params }}
